site_name: ProADV
site_url: https://github.com/farzadasgari/proadv
nav:
  - Home: "index.md"
  - About: "acoustic-Doppler-velocimeter.md"
  - Descriptive Stats: "statistics/descriptive.md"
  - Spread Stats: "statistics/spread.md"
  - Moments: "statistics/moment.md"
  - Series: "statistics/series.md"
  - Distributions: "statistics/distributions/normal.md"
  - 3d Kernel Density: "filtration/detection/three-dimensional-kernel-density.md"
  - Modified 3d Kernel Density: "filtration/detection/modified-three-dimensional-kernel-density.md"
  - Acceleration Thresholding: "filtration/detection/acceleration.md"
  - Phase-Space Thresholding: "filtration/detection/phase-space.md"
  - 3d Phase-Space Thresholding: "filtration/detection/three-dimensional-phase-space.md"
  - Velocity Correlation: "filtration/detection/velocity-correlation.md"
  - Bivariate Kernel Density: "filtration/detection/kernel-density.md"
  - Replacement: "filtration/replacement/replacement.md"


theme: "readthedocs"
